### ISSUE TITLE
Import wallet failed

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/wallet-next#105]
User has a 24 word seed key, which he imported but shows no balance. 
User also has 29 word seed key, but that gives error wallet already exists. 

Stellar: GAMF7KL7GL5QRDF5KWOMTDLNOOAVDXCK3EPQJXGTD3O2CI4GHVCXFJGC
Rivine: 01f4aa9ec151795199681dc44b302629dbc72002ccc524ef2fdb3d3535ac0081f54d4d5fbb8730
3Bot name: kristofdeguchtenaere.3bot
![photo_2022-04-01 16 31 00](https://user-images.githubusercontent.com/31733464/161284406-44ffc364-7666-4298-838d-34c81e03a017.jpeg)
![photo_2022-04-01 16 30 57](https://user-images.githubusercontent.com/31733464/161284413-1ee5b82c-3183-4c26-bda3-73af25cd37b1.jpeg)

**Comment by sabrinasadik** [comment]
@robvanmieghem pls check if it's a conversion issue or a wrong seed key

**Comment by robvanmieghem** [comment]
The Stellar address matches the rivine address and no conversion happened yet

**Comment by sabrinasadik** [comment]
@LennertDefauw1 @JonasWijne

**Comment by ken-de-moor** [comment]
Rivine conversions aren't supported in wallet v3, used was placed back to wallet v2 to do conversion.

**Comment by sabrinasadik** [comment]
User tried it again on wallet v2, still getting error. 
![WhatsApp Image 2022-05-31 at 5 41 51 PM](https://user-images.githubusercontent.com/31733464/171346506-fea57d87-d31d-43ee-ae35-45bd0bc85fda.jpeg)

**Comment by sabrinasadik** [comment]
@robvanmieghem any update? User is not happy

**Comment by robvanmieghem** [comment]
The account has been activated and has the required trustlines.

No conversion happened yet, I'll handle that.

**Comment by robvanmieghem** [comment]
the conversion has been done
