### ISSUE TITLE
Showing logs in app takes inconsistent taps

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/wallet-next#106]
IOS: 9 fast taps or 5 taps with a second in between of each tap
Ash reports it takes only 1 tap for him on Android 

https://user-images.githubusercontent.com/31733464/161523258-a219456b-ea4e-41a4-9487-eeb5ed986ce7.mp4

**Comment by JonasWijne** [comment]
I hypothesize that IOS sees these taps as double taps and are not registered as `click`.

A fix could be to add a touchend to these `clicks`.
