### ISSUE TITLE
Wallet shows blank screen 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/wallet-next#108]
Initial load time too long 
![photo_2022-04-04 13 00 10](https://user-images.githubusercontent.com/31733464/161530422-7b35fc5d-3637-4c93-86bd-d4ff9ca28846.jpeg)

**Comment by sabrinasadik** [comment]
Examples:
1. jvonline01.3Bot - Android 10
2. michaelww.3bot - Iphone x version 14.8.1 - app version 3.5.0 -157

**Comment by LennertDefauw1** [comment]
Issue found and made wallet already IOS 14.5+ compatible, IOS 14.5 and less still doesnt work due a transpiliation error which still has to be solved. Will discuss this topic with Jonas next week.

**Comment by sabrinasadik** [comment]
Status?

**Comment by LennertDefauw1** [comment]
Is fixed by IOS 15 as min requirement
