### ISSUE TITLE
Can't send tokens to token issuer.

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/wallet-next#116]
EDIT by ken with some more info: Issue is that the token issuer doesn't have a trustline to their own asset. This is an edge case where normally it's not possible to send tokens to something that doesn't have a trustline, except for this one wallet.

TFTA to TFT conversion needs to happen to address GBUT4GP5GJ6B3XW5PXENHQA7TXJI5GOPW3NF4W3ZIW6OOO4ISY6WNLN2
as instructed on https://library.threefold.me/info/threefold#/tokens/threefold__tfta_to_tft

Getting error "Destination account has no trustline for asset" which is incorrect.

**Comment by ken-de-moor** [comment]
@JonasWijne this issue returned on beta somehow.

![image](https://user-images.githubusercontent.com/59569757/166483276-a022ca9d-d3c4-4160-a895-15b3197ca9c9.png)
