### ISSUE TITLE
Wallet keeps spinning - no data yet 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/wallet-next#122]
3Bot: renaulter.3bot

Version One UI 3.1

Version Android 11

Samsung A41

**Comment by LennertDefauw1** [comment]
https://user-images.githubusercontent.com/43674202/163186599-14217cab-7991-4e3e-99ae-f3973ac9a53c.MOV

**Comment by LennertDefauw1** [comment]
![image](https://user-images.githubusercontent.com/43674202/163186737-e1dd3d91-6ac7-4f60-9a2e-8805841c2e09.png)


coming inside this if

**Comment by LennertDefauw1** [comment]
Android System Webview wasnt updated on his device

Updating this app solved the issue
