### ISSUE TITLE
Need list of all wallet addresses that still have locked tokens

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/wallet-next#124]
Talked to @robvanmieghem he'll write a script for that

**Comment by robvanmieghem** [comment]
@sabrinasadik do you also need the unlocktimes?

**Comment by robvanmieghem** [comment]
https://github.com/threefoldfoundation/tft-stellar/blob/master/scripts/timelocked.py

output is csv (owner account, TFT, escrow account)
in the readme next to the script is explained how to set up your virtual env to run the script
