### ISSUE TITLE
Farmer migration keeps loading 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/wallet-next#130]
Since importing tfchain secret to the wallet, the farmer migration keeps loading. Tried same 3bot account (sabrinasadik) on both Android & iOS, same result.

**Comment by JonasWijne** [comment]
this is caused by data sync between farmer and wallet v3.

wallet v3 has a newer data model than farmer

solution is to deploy the newer farmer code, but this should first go through full regression
