### ISSUE TITLE
Wrong balance showed on TfchainMain wallet

### ISSUE THREAD

**Issue by archit3kt** [threefoldtech/wallet-next#152]
Hi there,

I'm using latest version of the wallet on the PlayStore

the TfchainMain wallet does not show the right amount of TFT, which I can see from the TFchainPortal

Wallet address is 5DFFkobnNqvj2ZDXiX8AokFSuVJg6usTNz6vdq2RU65YvmwF

At your disposal for further infos

**Comment by sabrinasadik** [comment]
Can we get your 3bot name pls?

**Comment by archit3kt** [comment]
This is archit3kt

**Comment by sabrinasadik** [comment]
Hi! Could you let us know if this is still an issue? If yes, please provide us a screenshot of those wallets (TFConnect App and Portal). Thx!

**Comment by archit3kt** [comment]
Hi Sabrina, the two following screenshots are from the app and testnet portal

![Screenshot_2022-05-13-10-42-48-146_org jimber threebotlogin](https://user-images.githubusercontent.com/32200831/168246841-d754fd93-00f2-4f80-8f65-ffcd48ac64d1.jpg)

![Screenshot_20220513_104410](https://user-images.githubusercontent.com/32200831/168246868-83a7eac6-512f-45b7-9697-2c622a021b6f.png)

Another bug : on testnet portal, when I click on bridge tft from stellar, and I scan the QR code in the app, I've got the following error message

![Screenshot_2022-05-13-10-45-07-113_org jimber threebotlogin](https://user-images.githubusercontent.com/32200831/168246990-d43babcb-6238-4268-a724-25821fe067cb.jpg)

Still the inputs are completed correctly and the transfer is working.

Hopes it will help

**Comment by sabrinasadik** [comment]
App = production mainnet
Testnet portal = different production network 

Which explains the difference.
