### ISSUE TITLE
alert on no balance after scanning qr should be changed

### ISSUE THREAD

**Issue by JonasWijne** [threefoldtech/wallet-next#158]
![image](https://user-images.githubusercontent.com/6184820/168019154-baf499f1-a065-40e6-a4d4-322afd181f5e.png)

**Comment by xmonader** [comment]
While this was merged on 12/may it still reported by kds again on 18th june.

**Comment by ken-de-moor** [comment]
@JonasWijne this fix was in our staging build right? But not live on production yet? Kristof just reported the issue again live in production right now.

**Comment by ken-de-moor** [comment]
Fixed and being deployed today. Personally validated on beta.
