### ISSUE TITLE
Conversion issue Rivine - Stellar 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/wallet-next#160]
It seems 560 287.6268448 TFT is still locked 
https://horizon.stellar.org/accounts/?signer=GD5UBZMGQYJLVXWBJRWOJYLFQVKTWBNCR7EHNUN3MCO3DY2UHPCI7VEL

Pierre.3bot
Stellar: GD5UBZMGQYJLVXWBJRWOJYLFQVKTWBNCR7EHNUN3MCO3DY2UHPCI7VEL
Rivine: 018f1db57fa2b5bbde751503219853910054e6ef8821512be8e5d389873d5343eabfad95d0a435

![Screenshot 2022-05-31 at 13 26 56](https://user-images.githubusercontent.com/31733464/171186564-91e80dcd-3f84-4651-b098-ef60e52f828a.png)

![photo_2022-05-31 15 36 37](https://user-images.githubusercontent.com/31733464/171186677-b4beaeee-1bb6-433b-b065-b13472698de4.jpeg)

**Comment by sabrinasadik** [comment]
@LennertDefauw1 this should be fixed now or not?

**Comment by sabrinasadik** [comment]
@robvanmieghem please check

**Comment by LennertDefauw1** [comment]
Can you ask the user if this issue is fixed? @sabrinasadik 

Was probably the locked tokens issue which is solved.

**Comment by sabrinasadik** [comment]
Not fixed yet

**Comment by robvanmieghem** [comment]
note to myself: original conversion happened at 2021-08-26 15:52:53 UTC

**Comment by robvanmieghem** [comment]
extra free TFT's have been issued

**Comment by sabrinasadik** [comment]
@LennertDefauw1 next step: put him back on v2 wallet so we can unlock the tokens

**Comment by sabrinasadik** [comment]
Tokens showing now! Thanks for the work guys
