### ISSUE TITLE
Story: add dedicated node and validator deployment.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/wallet-next#161]
See https://github.com/threefoldtech/home/issues/1257

This is for the app side story.

Needed: 
- [ ] User flow + UI. Where and how to integrate this functionality.
- [ ] Endpoints/documentation on what calls to do to "mark a node as dedicated" and to "deploy a validator"

**Comment by sasha-astiadi** [comment]
@ken-de-moor is this story still valid for 3.7? if yes please put in project

**Comment by ken-de-moor** [comment]
https://github.com/threefoldtech/home/issues/1257
