### ISSUE TITLE
User should be able to delete a wallet in the app 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/wallet-next#162]
Is it possible to simply 'hide' that wallet so it's not visible for the user, unless they import that seed key again?

**Comment by ken-de-moor** [comment]
Proposed change:

Delete option for a wallet, with clear warning.

Delete would de-couple that wallet from the Threefold Connect account. The secret would need to be used again in the import flow to couple the wallet again.

Hiding wallets would cause lots of issues with other flows where we check all coupled wallets, so is not recommended. It should be a full delete/decouple.

**Comment by sabrinasadik** [comment]
Agreed

**Comment by sabrinasadik** [comment]
@ken-de-moor let me know when this is implemented please

**Comment by ken-de-moor** [comment]
@sabrinasadik it's already implemented and live on production.

Any wallet except the first initial one can now be deleted.
