### ISSUE TITLE
Tokens not unlocking 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/wallet-next#173]
Example

Account: m@3bot
Address: GC6KX4ZSKVMKH4PHXHAT6AOHZRUBWDYZ2TSPM5GBO64R6HJSJTSOELMO

**Comment by LennertDefauw1** [comment]
@sabrinasadik can you confirm this is solved?

**Comment by sabrinasadik** [comment]
Resolved, thanks!
