### ISSUE TITLE
TF Wallet - It should be possible to send directly via a 3bot account name

### ISSUE THREAD

**Issue by DeanVerjans** [threefoldtech/wallet-next#177]
# Account address namespace proposal

## General
The implementation of a account namespace, this makes it possible to let Account account owners decide to save wallet addresses inside a namespace. The namespace contains all the addresses of the different chains and can be used within the wallet to send assets directly to a account name.

## Implementation
Within the wallet there should be a setting to enable this feature, this will create a namespace for the account owner on pkid. In there  will be a snapshot saved of the account's wallet owner current addresses of all the different chains installed in the wallet.

### Pkid
- [x] Conversion from Python to JS
- [x] Namespace endpoints
   - [x] Get a user's namespace
   - [x] Create/update your own namespace
- [x] Verification of the create/update endpoint
- [x] Validation of the wallet addresses given on creation/update

### Pkid Node Client
- [x] Add Typescript support
- [x] Add namespace endpoints

### Wallet frontend
- [x] Add a Modal to make wallets public on the first startup
- [x] Add a Button in the settings to add a wallet to your own namespace
- [x] Add a label to identify if the wallet is public or private
- [x] Add an info icon to give the user more info about namespacing wallets
- [x] Add Callback to sign data with the Main Private Key of the user
- [x] Make it possible to use the username to send funds to
   - [x] Add a dropdown to the address box in the send overview
   - [x] Only show the addresses of the selected chain
   - [x] Add the possibility to select a namespace wallet

### Namespace route

`/<3botname>`

### Namespace format

Collection of all the wallet addresses:
```json

[
  {
    "name": "<wallet-name>",
    "chains": {
       [ChainTypes.STELLAR]: "<wallet-stellar-address>",
       [ChainTypes.SUBSTRATE]: "<wallet-substrate-address>"
    }
  },
  ...
]
```

### Create/update Account namespace

To Create or update the account namespace the owner have to sign the wallet metadata with their private key. So the data can then be verified with the public key of the user to ensure the data is valid.

#### Body
```json
  "<signed-wallet-snapshot>"
```

There should be validation to validate if the given address is compatible with the given chain.

### Delete Account namespace
TBD

### Get Account namespace

Inside the wallet the user gives a account name, the wallet resolves the account address via the wallet backend. 

#### Response
```json
{
  "data": "<signed-wallet-snapshot>",
  "verified": "<boolean>"
}
```

It's then possible to get all the wallet addresses of a specific chain that can be used to send tokens to via the wallet.

**Comment by ken-de-moor** [comment]
- Newly created wallets => Always public. Should be changed to private in settings if they need to.
- Show public/private in overview of the wallets.
- Don't show .3bot in the frontend. Only in backend.
- In settings just call it "Make this wallet public" and "Make this wallet private".

**Comment by ken-de-moor** [comment]
![image](https://user-images.githubusercontent.com/59569757/186382729-3c06df1e-c7bb-4390-89e4-d8f683b5a0a0.png)

**Comment by LennertDefauw1** [comment]
**Progress report:**

This feature has been implemented and is live on staging

**Comment by sasha-astiadi** [comment]
please put some screenshots/ visual to show on forum @ken-de-moor

**Comment by sasha-astiadi** [comment]
all existng accounts will be private, new onespublic, but ppl can choose to turn it into private / public... (privacy setting always available)...

please show us this prompt as well... 

- screenshot of sending token
- screenshot of new wallet prompt
- screenshot of wallet privacy setting

**Comment by sasha-astiadi** [comment]
what if a user have multiple wallets,

when i send tokens to his account, with only mentioning the username, which wallet will it goes to?

**Comment by LennertDefauw1** [comment]
@sasha-astiadi new features in farming update:


Improvement in performance of farmers tab
Added node status in details of specific farm (online / offline node)
Delete farm functionality has been added
